# -*- coding: utf-8 -*-
"""start_here.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/geacomputing/UCY2Sept/blob/main/Python/jupyterNotebooks/start_here.ipynb

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/geacomputing/UCY2Sept/blob/main/Python/jupyterNotebooks/start_here.ipynb)

# 🛰️ UCY2Sept: Getting Started on Colab

Welcome to the **UCY2Sept** project running on Google Colab.

This notebook will:
- Clone the entire GitHub repository
- Set up the environment
- Provide quick links and tips to navigate the repo
"""

import sys
import os


# Python version
print(f"Python version: {sys.version}")

"""## 🔁 Step 1: Clone the Repository"""

# Commented out IPython magic to ensure Python compatibility.
# Remove default sample_data folder if it exists
!rm -rf /content/sample_data

# Clone the GitHub repo (replace with your fork if needed)
!git clone https://github.com/geacomputing/UCY2Sept.git

# Move into the project folder
# %cd UCY2Sept

print("You are now in the right folder")

print(3*"\n")
print("Folder Content:")
print(30*"-")
# Optional: check folder structure
!ls

"""## 🛠️ Step 2: Add repo to Python path"""

# Add current repo to Python path
repo_path = os.getcwd()
if repo_path not in sys.path:
    sys.path.append(repo_path)

print("Repository added to Python path.")

# Install packages from requirements.txt (needed for this session)
! pip install -r requirements.txt

# List of packages to check
packages = [
    "xarray",
    "netCDF4",
    "cartopy",
    "matplotlib",
    "pandas"
]

# Compute the maximum length of package names, for aligned printing
maxlen = max(len(pkg) for pkg in packages)

# Track whether any import has failed
import_failed = False


print("\n👉 Testing installation of required packages\n")

# Attempt to import each package
for pkg in packages:
    try:
        module = __import__(pkg)
        version = getattr(module, '__version__', 'Version not found')
        print(f"✔️Successfully imported   : {pkg:<{maxlen}}   (version: {version})")
    except ImportError:
        print(f"❌ Failed to import        : {pkg:<{maxlen}}")
        import_failed = True
    except Exception as e:
        print(f"❌ Error importing         : {pkg:<{maxlen}}   ({e})")
        import_failed = True

# Final warning if anything failed
if import_failed:
    print("\n[+] WARNING:")
    print("\tAt least one package failed to import.")
    print('\tHave you installed all required packages using: "! pip install -r requirements.txt" ?')
    print('\tNote the "!" sign — it is needed when running from Jupyter or Colab notebooks.')
else:
  print("\n🛠️ INFO:")
  print("\tGITHUB material and scripts downloaded.Packages installed correctly.\n\n✅ You are good to go.")